config/routes.rb
Refinery::Core::Engine.routes.draw do

  namespace :snippets, :path => '' do
    namespace :admin, :path => Refinery::Core.backend_route do
      resources :snippets do
        collection do
          post :update_positions
        end
        
        resources :snippets_page_parts do
          member do
            get 'add'
            get 'remove'
          end
        end
      end
    end
  end
  
end

app/models/refinery/after_page_part_snippet.rb
require File.expand_path('../page_part_snippet.rb', __FILE__)

module Refinery
  class AfterPagePartSnippet < PagePartSnippet

    default_scope -> { order(position: :asc) }

    def position_to_part
      'after'
    end
  end
end

app/models/refinery/before_page_part_snippet.rb
require File.expand_path('../page_part_snippet.rb', __FILE__)

module Refinery
  class BeforePagePartSnippet < PagePartSnippet

    default_scope -> { order(position: :asc) }

  end
end

app/models/refinery/page_part_snippet.rb
module Refinery
  class PagePartSnippet < ActiveRecord::Base

    self.abstract_class = true

    belongs_to :snippet, foreign_key: :snippet_id
    belongs_to :page_part, foreign_key: :page_part_id

    validates_uniqueness_of :snippet_id,  scope: [:page_part_id]

    delegate :title, :body, to: :snippet

    def canonical_friendly_id
      "#{snippet.canonical_friendly_id}-#{position_to_part}-#{page_part.title}"
    end

    def position_to_part
      'before'
    end

    def render(context)
      presenter.new(self, context).wrapped_html
    end

    def presenter
      @presenter ||= "Refinery::Snippets::#{snippet.snippet_type.classify}SnippetPresenter".safe_constantize
    end
  end
end

app/models/refinery/snippet.rb
module Refinery
  class Snippet < ActiveRecord::Base
    extend GlobalizeFinder

    TYPES = ['text', 'template']

    before_validation :create_canonical_friendly_id

    validates :title, presence: true, uniqueness: true
    validates :canonical_friendly_id, presence: true, uniqueness: true

    translates :title, :body

    default_scope {
      includes(:translations).joins(:translations)
    }

    def title
      return self[:title] if self[:title].present?
      translation = translations.detect {|t| t.title.present? }
      translation.title if translation
    end

    private

    def create_canonical_friendly_id
      self.canonical_friendly_id = (canonical_friendly_id.presence || title.presence).parameterize
    end
  end
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base

  acts_as_indexed :fields => [:title, :body]

  validates :title, :presence => true, :uniqueness => true

  translates :body

  has_many :snippet_page_parts, :dependent => :destroy
  has_many :page_parts, :through => :snippet_page_parts

  scope :for_page, lambda { |page|
    raise RuntimeError.new("Couldn't find Snippet for a nil Page") if page.blank?
    joins(:page_parts => :page).where(:pages => {:id => page.id})

  }

  scope :before, -> { where(:snippets_page_parts => {:before_body => true}) }
  scope :after, -> { where(:snippets_page_parts => {:before_body => false}) }
  
  # rejects any page that has not been translated to the current locale.
  scope :translated, lambda {
    pages = Arel::Table.new(Snippet.table_name)
    translations = Arel::Table.new(Snippet.translations_table_name)

    includes(:translations).where(
                                  translations[:locale].eq(Globalize.locale)).where(pages[:id].eq(translations[:snippet_id]))
  }

  def pages
    Page.for_snippet(self)
  end

  def before?(part)
    part.snippets.before.include? self
  end

  def after?(part)
    part.snippets.after.include? self
  end

end

app/models/snippet_page.rb
class SnippetPage < ActiveRecord::Base
  
  self.table_name = 'snippet_page'
  
  belongs_to :snippet, :foreign_key => :snippet_id
  belongs_to :page, :foreign_key => :page_id
  
  validates_uniqueness_of(:snippet_id, :scope => :page_id)

  before_save do |snippet_page|
    snippet_page.position = (SnippetPage.where('page_id = ?', snippet_page.page_id).maximum(:position) || -1) + 1
  end
  
end

app/models/snippet_page_part.rb
class SnippetPagePart < ActiveRecord::Base
  
  self.table_name = 'snippets_page_parts'
  
  belongs_to :snippet, :foreign_key => :snippet_id
  belongs_to :page_part, :foreign_key => :page_part_id

  validates_uniqueness_of :snippet_id,  :scope => [:page_part_id, :before_body]
  
  before_save do |snippet_page_part|
    snippet_page_part.position = (SnippetPagePart.where('page_part_id = ?', snippet_page_part.page_part_id).maximum(:position) || -1) + 1
  end
  
end

app/controllers/refinery/admin/snippets_controller.rb
module Refinery
  module Admin
    class SnippetsController < ::Refinery::AdminController

      crudify :'refinery/snippet'

      def snippet_params
        params.require(:snippet).permit([:title, :body, :canonical_friendly_id])
      end

      def redirect_url
        if @snippet && @snippet.persisted?
          refinery.edit_admin_snippet_path(@snippet.id,
            locale: params[:switch_frontend_locale].presence || Globalize.locale)
        else
          refinery.admin_snippets_path
        end
      end

    end
  end
end

app/controllers/refinery/snippets/admin/snippets_controller.rb
module Refinery
  module Snippets
    module Admin
      class SnippetsController < ::Refinery::AdminController

        crudify :snippet, :xhr_paging => true
        
        def create
          if (@snippet = Snippet.create(snippet_params)).valid?
            (request.xhr? ? flash.now : flash).notice = t(
              'refinery.crudify.created',
              :what => "#{@snippet.title}"
            )

            unless request.xhr?
              redirect_to (params[:continue_editing] =~ /1/ ? edit_snippets_admin_snippet_path(@snippet) : snippets_admin_snippets_url)
            else
              response = Hash.new
              response['redirect'] = edit_snippets_admin_snippet_path(@snippet) if params[:continue_editing]
              render :json => response
            end

          else
            unless request.xhr?
              render :action => 'new'
            else
              html_snippets = Hash.new
              html_snippets['flash_container'] = render_to_string(:partial => "/refinery/admin/error_messages",
                                                                  :locals => {
                                                                    :object => @snippet,
                                                                    :include_object_name => true
                                                                  })
              render :json => {'snippets' => html_snippets}
            end
          end
        end

        private

        def snippet_params
          params.require(:snippet).permit(:title, :body)
        end
      end
    end
  end
end

app/controllers/refinery/snippets/admin/snippets_page_parts_controller.rb
module Refinery
  module Snippets
    module Admin
      class SnippetsPagePartsController < Admin::BaseController
        
        def add
          @page = Page.find(params[:id])
          @part = PagePart.find(params[:part_id])
          @snippet = Snippet.find(params[:snippet_id])
          before_body = params[:before_body] == 'true' ? true : false
          
          sp = SnippetPagePart.new(:page_part => @part, :snippet => @snippet, :before_body => before_body)

          if sp.save
             flash[:notice] = "Snippet #{@snippet.title} was successfully added."
          end
          
          render :layout => false if request.xhr?
        end

        def remove
          @page = Page.find(params[:id])
          @part = PagePart.find(params[:part_id])
          @snippet = Snippet.find(params[:snippet_id])
          before_body = params[:before_body] == 'true' ? true : false

          sp = SnippetPagePart.where(:page_part_id => @part, :snippet_id => @snippet, :before_body => before_body)
          
          removed = sp.first.destroy() unless sp.empty?

          if removed
             flash[:notice] = "Snippet #{@snippet.title} was successfully removed."
          end
          
          render :layout => false if request.xhr?
        end
      end
    end
  end
end

app/helpers/refinery/admin/snippets_helper.rb
module Refinery
  module Admin
    module SnippetsHelper

      def snippet_meta_information(snippet)
        meta_information = ActiveSupport::SafeBuffer.new
        meta_information << content_tag(:span, class: 'label') do
          ::I18n.t(snippet.snippet_type, scope: 'refinery.admin.snippets.snippet')
        end

        meta_information << content_tag(:span, class: 'label important') do
          ::I18n.t('untranslated', scope: 'refinery.admin.pages.page')
        end if snippet.translation.new_record?

        meta_information
      end

    end
  end
end

app/views/refinery/admin/pages/tabs/_snippets.html.erb
<div class="ui-tabs ui-tabs-vertical clearfix" id="snippets-page-parts" style="padding-top: 10px;" >
<% parts = @page.parts.select {|p| p.active } %>
  <ul style="margin-top: 29px;">
  <% page_url = @page.new_record? ?
        refinery.new_admin_page_path( parent_id: params[:parent_id] ) :
        refinery.edit_admin_page_path( id: @page.nested_url ) %>

  <% parts.each_with_index do |part, i| %>
    <li>
      <%= link_to t(part.title, scope: 'refinery.admin.pages.parts'), "#{page_url}#snippets-page-parts-#{i}" %>
    </li>
  <% end %>
  </ul>
  <%= render partial: '/refinery/admin/pages/tabs/snippets_field', collection: parts, as: :part %>
</div>

app/views/refinery/admin/pages/tabs/_snippets_field.html.erb
<%
  # this is first implementation and should be cleaned eventualy
  # todo: clean
  snippets = Refinery::Snippet.all.to_a
  snippets_before_ids = part.before_page_part_snippets.map(&:snippet_id)
  before_snippets = part.before_page_part_snippets.map(&:snippet) | snippets
  part_bkey = "snippets_before_#{part.id || part.title}"
  if params[part_bkey]
    params_snippets = params[part_bkey].map {|s| s[1][:snippet_id] }
    before_snippets.sort! {|a, b| params_snippets.index(a.id.to_s) <=> params_snippets.index(b.id.to_s) }.map(&:id)
  end

  snippets_after_ids = part.after_page_part_snippets.map(&:snippet_id)
  after_snippets = part.after_page_part_snippets.map(&:snippet) | snippets
  part_akey = "snippets_after_#{part.id || part.title}"
  if params[part_akey]
    params_snippets = params[part_akey].map {|s| s[1][:snippet_id] }
    after_snippets.sort! {|a, b| params_snippets.index(a.id.to_s) <=> params_snippets.index(b.id.to_s) }.map(&:id)
  end


%>

<div id="<%= "snippets-page-parts-#{part_counter}" %>" class="ui-tabs-panel clearfix">
  <div class="hemisquare">
  <%= checkboxes do -%>
    <h3><%= t('.before_part_body') %></h3>
    <ul class="records checkboxes ui-sortable">

    <% before_snippets.each_with_index do |snippet, index| %>
      <li>
        <% snippet_activated = params[part_bkey] && (!params[part_bkey].map {|s| s[1] }.select {|s| s[:snippet_id] == snippet.id.to_s && s[:active] == "1" }.empty?) %>
        <% snippet_activate_by_default = !!Refinery::Snippets.activate_by_default[:"#{snippet.canonical_friendly_id.gsub('-', '_')}_before_#{part.title}"] %>
        <% snippet_persisted = snippets_before_ids.include?(snippet.id) %>
        <% if snippet_persisted %>
          <%= hidden_field_tag "#{part_bkey}[#{index}][id]", part.before_page_part_snippets.select {|s| s.snippet.id == snippet.id }.first.id %>
        <% end %>
        <%= hidden_field_tag "#{part_bkey}[#{index}][snippet_id]", snippet.id %>
        <%= hidden_field_tag "#{part_bkey}[#{index}][active]", 0 %>
        <%= check_box_tag "#{part_bkey}[#{index}][active]", 1,
                    ((snippet_persisted || snippet_activate_by_default) && snippet_activated.nil?) || snippet_activated,
                    id: "#{part_bkey}_#{index}" %>
        <%= label_tag nil, snippet.title,
                    class: 'stripped',
                    for: "#{part_bkey}_#{index}" %>
      </li>
    <% end %>
    </ul>
  <% end %>
  </div>
  <div class="hemisquare right-side">

  <%= checkboxes do -%>
    <h3><%= t('.after_part_body') %></h3>
    <ul class="records checkboxes ui-sortable">

    <% after_snippets.each_with_index do |snippet, index| %>
      <li>
        <% snippet_activated = params[part_akey] && (!params[part_akey].map {|s| s[1] }.select {|s| s[:snippet_id] == snippet.id.to_s && s[:active] == "1" }.empty?) %>
        <% snippet_activate_by_default = !!Refinery::Snippets.activate_by_default[:"#{snippet.canonical_friendly_id.gsub('-', '_')}_after_#{part.title}"] %>
        <% snippet_persisted = snippets_after_ids.include?(snippet.id) %>
        <% if snippet_persisted %>
          <%= hidden_field_tag "#{part_akey}[#{index}][id]", part.after_page_part_snippets.select {|s| s.snippet.id == snippet.id }.first.id %>
        <% end %>
        <%= hidden_field_tag "#{part_akey}[#{index}][snippet_id]", snippet.id %>
        <%= hidden_field_tag "#{part_akey}[#{index}][active]", 0 %>
        <%= check_box_tag "#{part_akey}[#{index}][active]", 1,
                    ((snippet_persisted || snippet_activate_by_default) && snippet_activated.nil?) || snippet_activated,
                    id: "#{part_akey}_#{index}" %>
        <%= label_tag nil, snippet.title,
                    class: 'stripped',
                    for: "#{part_akey}_#{index}" %>
      </li>
    <% end %>
    </ul>
  <% end %>
  </div>
</div>

app/views/refinery/admin/snippets/_actions.html.erb
<ul>
  <li>
    <%= link_to t('.create_new'), refinery.new_admin_snippet_path,
                class: 'icon-small icon-with-text add-icon' %>
  </li>
</ul>

<%= render 'refinery/admin/actions_locale_picker', url: refinery.admin_snippets_path %>

app/views/refinery/admin/snippets/_form.html.erb
<%= form_for [refinery, :admin, @snippet],
            html: { data: { remote: true }} do |f| -%>
  <div class="clearfix">

    <%= render('/refinery/admin/locale_picker',
                (@snippet.new_record? ?
                  { url: 'new_admin_snippet_path' } :
                  { url: 'edit_admin_snippet_path', url_options: { id: @snippet } })
              ) if Refinery::I18n.frontend_locales.many? %>

    <div class="form-title">
      <h1>
      <% if @snippet.new_record? %>
        <%= t('new_snippet', scope: 'refinery.admin.snippets.actions') %>
      <% else %>
        <%= t('edit_snippet', scope: 'refinery.admin.snippets.actions') %>:
        <%= @snippet.title %>
      <% end -%>
      </h1>

      <div class="clearfix">
        <div class="meta-informations right-side">
          <%= snippet_meta_information(@snippet) unless @snippet.new_record? %>
        </div>
        <div class="breadcrumbs less-important">
          <p>
            <%= link_to refinery_plugin.title, refinery_plugin.url %>
          </p>
        </div>
      </div>
    </div>
  </div>

  <%= render '/refinery/admin/error_messages',
              object: f.object,
              include_object_name: true %>

  <div class="field">
    <%= f.label :title -%>
    <%= f.text_field :title, class: 'larger widest' -%>
  </div>

  <div class="field">
    <%= f.label :body -%>
    <% if @snippet.snippet_type == 'text' %>
      <%= f.text_area :body, rows: 20, class: 'widest' -%>
    <% else %>
      <%= f.text_field :body, class: 'widest' -%>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :canonical_friendly_id -%>
    <%= f.text_field :canonical_friendly_id -%>
  </div>

  <%= render partial: '/refinery/admin/form_actions',
              locals: {
                f: f
              } %>
<% end -%>

app/views/refinery/admin/snippets/_records.html.erb
<% if @snippets.any? %>
  <%= render partial: 'snippets' %>
<% else %>
  <p>
    <%= t('.no_items_yet') %>
  </p>
<% end %>

app/views/refinery/admin/snippets/_snippet.html.erb
<li class="clearfix record" id="<%= dom_id snippet %>">
  <span class="title">
    <%= snippet.title %>
  </span>
  <%= snippet_meta_information(snippet) %>
  <span class="actions">
    <%= link_to t('delete', scope: 'refinery.admin.record'),
                refinery.admin_snippet_path(snippet),
                class: 'delete confirm-delete nojs-hide icon-small delete-icon',
                title: t('.delete'),
                data: {
                  remote: true,
                  confirm: t('message', scope: 'refinery.admin.delete', title: snippet.title)
                },
                method: :delete %>

    <%= link_to t('edit', scope: 'refinery.admin.record'),
                refinery.edit_admin_snippet_path(snippet),
                class: 'icon-small edit-icon',
                title: t('.edit') %>

  </span>
</li>

app/views/refinery/admin/snippets/_snippets.html.erb
<%= will_paginate @snippets %>
<ul class="records">
  <%= render partial: 'snippet', collection: @snippets %>
</ul>
<%= will_paginate @snippets %>

app/views/refinery/admin/snippets/edit.html.erb
<%= render partial: 'form' %>

app/views/refinery/admin/snippets/index.html.erb
<section id="records">
  <%= render partial: 'records' %>
</section>
<aside id="actions">
  <%= render partial: 'actions' %>
</aside>

app/views/refinery/admin/snippets/new.html.erb
<%= render partial: 'form' %>

app/views/refinery/snippets/admin/pages/tabs/_snippets.html.erb
<div class="wym_skin_refinery page_part" id="page_snippet_picker">
  <%= render :partial => '/refinery/snippets/admin/pages/tabs/snippets_content', :locals => {:f => f} %>
</div>

app/views/refinery/snippets/admin/pages/tabs/_snippets_content.html.erb
<% if @page.new_record? %>
  <div class="msg alert"><%= t('.please_save_page_before') %></div>
<% else %>
  <div id="part-snippets-menu">
    <ul>
    <% @page.parts.each do |part|%>
      <li><%= link_to(part.title, :anchor => "part-#{part.id}") %> |</li>
    <% end %>
    </ul>
  </div>
  <%= render :partial => '/refinery/snippets/admin/pages/tabs/snippets_field', :collection => @page.parts, :as => :part %>
<% end %>

<% content_for :stylesheets do %>
  <%= stylesheet_link_tag 'page-snippet-picker' %>
<% end %>
<% content_for :javascripts do %>
  <%= javascript_include_tag 'page-snippet-picker' %>
<% end %>
<% content_for :javascripts do %>
  <%= javascript_include_tag 'part-snippets-select' %>
<% end %>

app/views/refinery/snippets/admin/pages/tabs/_snippets_field.html.erb
<div id="<%= "part-#{part.id}" %>" class="part-snippets">
  <div class="active-snippets block">
    <% if part.snippets.before.any? %>
      <h3><%= t('.before_body') %></h3>
      <ul>
        <%= render :partial => '/refinery/snippets/admin/pages/tabs/snippets_list_item', :collection => part.snippets.before, :as => :snippet, :locals => {:part => part, :before_body => true} %>
      </ul>
    <% end %>
    <% if part.snippets.after.any? %>
      <h3><%= t('.after_body') %></h3>
      <ul>
        <%= render :partial => '/refinery/snippets/admin/pages/tabs/snippets_list_item', :collection => part.snippets.after, :as => :snippet, :locals => {:part => part, :before_body => false} %>
      </ul>
    <% end %>
  </div>
  <div class="inactive-snippets block">
    <% inactive_snippets = Snippet.all %>
    <% if inactive_snippets.length > 0 %>
      <h3><%= t('.inactive') %></h3>
      <ul>
        <% inactive_snippets.each do |snippet| %>
          <li class='clearfix record <%= cycle('on', 'on-hover') %>' >
            <span class="title"><%= snippet.title %></span>
            <div class="actions">
              <% unless snippet.after?(part) %>
                <%= link_to t('.add_after_body'), {:controller => 'refinery/snippets/admin/snippets_page_parts', :action => 'add', :id => @page.id, :snippet_id => snippet.id, :part_id => part.id}, :class => 'add_icon add-snippet' %>
              <% else %>
                <span class="add_icon add-snippet"><%= t('.add_after_body') %></span>
              <% end %>
              <% unless snippet.before?(part) %>
                <%= link_to t('.add_before_body'), {:controller => 'refinery/snippets/admin/snippets_page_parts', :action => 'add', :id => @page.id, :snippet_id => snippet.id, :part_id => part.id, :before_body => 'true'}, :class => 'add_icon add-snippet' %>
              <% else %>
                <span class="add_icon add-snippet"><%= t('.add_before_body') %></span>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/refinery/snippets/admin/pages/tabs/_snippets_list_item.html.erb
<li class='clearfix record <%= cycle('on', 'on-hover') %>' >
  <span class='title'>
    <%= snippet.title %>
    <% if defined?(::Refinery::I18n) and ::Refinery::I18n.frontend_locales.many? and
           (locales = snippet.translations.collect{|t| t.locale}).present? %>
      <span class='preview'>
        <% locales.each do |locale| %>
          <%= refinery_icon_tag "flags/#{locale}.png", :size => '16x11' %>
        <% end %>
      </span>
    <% end %>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag('application_edit.png'), edit_snippets_admin_snippet_path(snippet),
        :title => t('.edit') %>
    <%= link_to refinery_icon_tag('delete.png'), url_for({:controller => 'refinery/snippets/admin/snippets_page_parts', :action => 'remove', :id => @page.id, :snippet_id => snippet.id, :part_id => part.id, :before_body => before_body}),
        :title => t('.remove'),
        :class => 'remove-snippet' %>
  </span>
</li>

app/views/refinery/snippets/admin/snippets/_actions.html.erb
<ul>
  <% if Refinery::Snippets::Admin::SnippetsController.searchable? %>
    <li>
      <%= render :partial => "/refinery/admin/search",
                  :locals => {
                    :url => snippets_admin_snippets_url
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), new_snippets_admin_snippet_url,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Refinery::Snippets::Admin::SnippetsController.sortable? and Snippet.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Snippets"),
                 snippets_admin_snippets_url,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Snippets"),
                 snippets_admin_snippets_url,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/refinery/snippets/admin/snippets/_form.html.erb
<%= form_for [:snippets, :admin, @snippet] do |f| -%>
  <%= render :partial => "/refinery/admin/error_messages", :locals => {
          :object => @snippet,
          :include_object_name => true
        } %>
  

  <%= render '/refinery/admin/locale_picker', 
               :current_locale => Globalize.locale if defined?(::Refinery::I18n) %>
    
  <div class='field'>
    <%= f.label :title -%>
    <%= f.text_field :title, :class => 'larger widest' -%>
  </div>
  <br />
  <div class='field'>
    <div class='clearfix ui-tabs ui-widget ui-widget-content ui-corner-all'>
      <div>
        <% [:body].each do |part| %>
          <div>
            <%= f.text_area part, :rows => 20, :class => 'wymeditor widest' -%>
          </div>
        <% end %>
      </div>
    </div>

  <%= render :partial => 'form_actions',
              :locals => {
                :f => f,
                :continue_editing => true,
                :delete_title => t('delete', :scope => 'admin.snippets.snippet'),
                :delete_confirmation => t('message', :scope => 'refinery.admin.delete', :title => @snippet.title)
              } %>
<% end -%>
<% content_for :javascripts do %>

<% end %>

app/views/refinery/snippets/admin/snippets/_form_actions.html.erb
<div class="form-actions">
  <div class="form-actions-left">
    <%= hidden_field_tag :continue_editing, 1 %>

    <%= submit_tag t('save', :scope => 'refinery.admin.form_actions'),
      :id => 'save-button',
      :class => 'wymupdate button no-js-hide' %>

    <%= submit_tag t('save_and_continue_editing', :scope => 'refinery.admin.continue_editing'),
      :id => 'save-continue-button',
      :class => "wymupdate button" %>

  </div>
</div>
<% content_for :javascripts do %>
<script type="text/javascript">
  $(document).ready(function () {
    var save_button = $('#save-button'),
        save_continue_button = $('#save-continue-button'),
        continue_input = $('#continue_editing');
    
    save_button.bind('click', function () {
      continue_input.val('0');
    });

    save_continue_button.bind('click', function () {
      continue_input.val('1');
    });
  });
</script>
<% end %>

app/views/refinery/snippets/admin/snippets/_locale_picker.html.erb
<input type='hidden' name='switch_locale' id='switch_locale' value='<%= local_assigns[:current_locale] %>' />
<% if defined?(::Refinery::I18n) and ::Refinery::I18n.frontend_locales.many? and 
    (locales = ::Refinery::I18n.frontend_locales).present? %>
  <ul id='switch_locale_picker' class='clearfix'>
    <% locales.each do |locale| %>
      <li<%= " class='selected'" if locale.to_s == local_assigns[:current_locale].to_s %>>
        <%= link_to refinery_icon_tag("flags/#{locale}.png", :size => '48x33'),
                    url_for(:switch_locale => locale) %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/refinery/snippets/admin/snippets/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for_html', :scope => 'refinery.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @snippets.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'snippets' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'refinery.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/refinery/snippets/admin/snippets/_snippet.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(snippet) -%>">
  <span class='title'>
    <%= snippet.title %>
    <% if defined?(::Refinery::I18n) and ::Refinery::I18n.frontend_locales.many? and
          (locales = snippet.translations.collect{|t| t.locale}).present? %>
      <span class='preview'>
        <% locales.each do |locale| %>
          <%= refinery_icon_tag "flags/#{locale}.png", :size => '16x11' %>
        <% end %>
      </span>
    <% end %>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_snippets_admin_snippet_path(snippet),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), snippets_admin_snippet_path(snippet),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'refinery.admin.delete', :title => snippet.title),
        :method => :delete %>
  </span>
</li>

app/views/refinery/snippets/admin/snippets/_snippets.html.erb
<%= will_paginate @snippets %>
<%= render :partial => "sortable_list" %>

app/views/refinery/snippets/admin/snippets/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'snippet', :collection => @snippets %>
</ul>
<%= render :partial => "/refinery/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/refinery/snippets/admin/snippets/edit.html.erb
<%= render :partial => "form" %>

app/views/refinery/snippets/admin/snippets/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/refinery/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Refinery::Snippets::Admin::SnippetsController.sortable? and Snippet.count > 1 %>

app/views/refinery/snippets/admin/snippets/new.html.erb
<%= render :partial => "form" %>

app/views/refinery/snippets/admin/snippets_page_parts/add.html.erb
<%= render :partial => '/refinery/snippets/admin/pages/tabs/snippets_content' %>

app/views/refinery/snippets/admin/snippets_page_parts/remove.html.erb
<%= render :partial => '/refinery/snippets/admin/pages/tabs/snippets_content' %>